GET https://fullstackopen-notes-backend-2d6k.onrender.com/api/notes

###
POST https://fullstackopen-notes-backend-2d6k.onrender.com/api/notes HTTP/1.1
content-type: application/json

{
    "content": "sample",
    "important": true
}